### ISSUE TITLE
Dies after I say yes to a movie choice

### ISSUE THREAD

**Issue by ghost** [edouardpoitras/jasper-movies#2]
just makes garbled noises

**Comment by edouardpoitras** [comment]
Hey @mattcurrycom,

Can you try running jasper with the --local flag (command input mode) and post the output of a use case in this ticket?

**Comment by ghost** [comment]
sure

**Comment by ghost** [comment]
No handlers could be found for logger "cmuclmtk"

---
-             COMPUTER - THE TALKING COMPUTER           *
  *******************************************************
  JASPER: How can I be of service, Matthew?
  YOU: computer
  JASPER: I beg your pardon?
  YOU: movies
  JASPER: What movie?
  YOU: sneakers
  JASPER: Searching top five results for.  sneakers
  JASPER: Did you mean Sneakers (1992)?
  YOU: yes
  JASPER: Sneakers (1992).  Rating.  7.1 out of 10.  Runtime.  126 minutes.  Genres.  Comedy.  Crime.  Drama.  Mystery.  Thriller.  Plot.  A security pro finds his past coming back to haunt him, when he and his unique team are tasked with retrieving a particularly important item.  Directors.  Phil Alden Robinson.  Producers.  William M. Elvin.  Lawrence Lasker.  Walter F. Parkes.  Lindsley Parsons Jr.  Cast.  Jo Marr.  Gary Hershberger.  Robert Redford.  Sidney Poitier.  David Strathairn.  

It appears that its an issue with the output getting piped to the TTS. Maybe too much? It just makes a noise and quits.

**Comment by ghost** [comment]
I am using MaryTTS btw.

**Comment by edouardpoitras** [comment]
What branches of jasper and jasper-movies are you using?

If this issue was happening on jasper-movies' develop branch, then my latest commit will most likely fix your problem.
Note that the --local flag won't work in develop with the latest commit until the following pull request gets merged into jasper: https://github.com/jasperproject/jasper-client/pull/488

If you're still having issues, let me know.
